[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sme_vault = "FYyrCQQ2rEfZEBYDB9SqJefsfdYTWR3HdbBzexVfuKkp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=35a22f6e-ab56-4212-a804-bd88139fe332"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/*.ts'"
